create table public.skin_types (
    id bigint generated by default as identity primary key,
    name varchar(100) not null unique
);

create table public.skin_concerns (
    id bigint generated by default as identity primary key,
    name varchar(100) not null unique
);

create table public.hair_types (
    id bigint generated by default as identity primary key,
    name varchar(100) not null unique
);

create table public.user_profiles (
    user_id uuid primary key references auth.users(id) on delete cascade,
    skin_type_id bigint references public.skin_types(id) on delete set null,
    hair_type_id bigint references public.hair_types(id) on delete set null,
    min_budget numeric(10,2),
    max_budget numeric(10,2),
    onboarding_completed boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint valid_budget_range
        check (
            min_budget is null
            or max_budget is null
            or min_budget <= max_budget
        )
);

create table public.user_skin_concerns (
    user_id uuid not null
        references public.user_profiles(user_id)
        on delete cascade,

    skin_concern_id bigint not null
        references public.skin_concerns(id)
        on delete cascade,

    created_at timestamptz not null default now(),

    primary key (user_id, skin_concern_id)
);

insert into public.skin_types (name)
values
    ('Normal'),
    ('Kuru'),
    ('Yağlı'),
    ('Karma'),
    ('Hassas');

insert into public.skin_concerns (name)
values
    ('Akne'),
    ('Leke'),
    ('Kuruluk'),
    ('Siyah Nokta'),
    ('Kızarıklık'),
    ('Yaşlanma Karşıtı');

insert into public.hair_types (name)
values
    ('Normal'),
    ('Kuru'),
    ('Yağlı'),
    ('Boyalı'),
    ('İnce Telli'),
    ('Kalın Telli'),
    ('Kıvırcık'),
    ('Kepekli');