create table public.product_skin_types (
    product_id integer not null
        references public.products(id)
        on delete cascade,

    skin_type_id bigint not null
        references public.skin_types(id)
        on delete cascade,

    created_at timestamptz not null default now(),

    primary key (product_id, skin_type_id)
);

create table public.product_skin_concerns (
    product_id integer not null
        references public.products(id)
        on delete cascade,

    skin_concern_id bigint not null
        references public.skin_concerns(id)
        on delete cascade,

    created_at timestamptz not null default now(),

    primary key (product_id, skin_concern_id)
);

create table public.product_hair_types (
    product_id integer not null
        references public.products(id)
        on delete cascade,

    hair_type_id bigint not null
        references public.hair_types(id)
        on delete cascade,

    created_at timestamptz not null default now(),

    primary key (product_id, hair_type_id)
);

create table public.tags (
    id bigint generated by default as identity primary key,
    name varchar(100) not null unique
);

create table public.product_tags (
    product_id integer not null
        references public.products(id)
        on delete cascade,

    tag_id bigint not null
        references public.tags(id)
        on delete cascade,

    created_at timestamptz not null default now(),

    primary key (product_id, tag_id)
);

insert into public.tags (name)
values
    ('Vegan'),
    ('Parfümsüz'),
    ('Alkolsüz'),
    ('Non-comedogenic');